Create Fruzhin Java Host phase 2 proposal
pioneersprize/Polkadot-Pioneers-Prize pull request #12
Opened 2023-09-21 09:57 UTC by hgergov

Hello Pioneers Prize team,

We are pleased to present our project application through the submission of the fruzhin-java-host-phase-2.md 

It outlines the Fruzhin Java Host Full Node project objectives. We are committed to actively engaging with the curators' feedback, promptly integrating suggested changes, and ensuring the application's refinement. We are dedicated to providing transparent milestone updates and notifying the curators upon their completion, demonstrating our commitment to the project's progress.

Best Regards,
LimeChain team

2023-10-26 08:10 UTC, Noc2 requested changes
Thanks a lot for the application, and I'm sorry for the very late reply. Could you add  default deliverables 0a-0d of the [application template](https://github.com/pioneersprize/Polkadot-Pioneers-Prize/blob/main/applications/application-template.md#milestone-1-example--basic-functionality) to all milestone for which it makes sense?

2023-10-26 11:49 UTC, georg-getz commented
@Noc2 Hey David, I updated the proposal to include the default milestone deliverables where applicable.

2023-10-27 09:27 UTC, Noc2 approved these changes
Thanks for the update. I'm personally happy to go ahead with it and share it with the rest of the team.

2023-11-02 07:28 UTC, xlc approved these changes

2023-11-08 13:12 UTC, rrtti approved these changes

2023-11-08 16:10 UTC, merged