reed solomon perf improvements proposal
pioneersprize/Polkadot-Pioneers-Prize pull request #2
Opened 2023-07-19 08:54 UTC by drahnr

2023-07-19 20:31 UTC, burdges commented
LGTM

2023-07-21 11:11 UTC, ordian reviewed
Hey Bernhard :)

When exploring SIMD, would be great to do runtime feature detection, like in https://github.com/dalek-cryptography/curve25519-dalek/pull/523

2023-07-21 11:11 UTC, ordian commented on applications/reed-solomon-perf.md
> +* introduce SMID instructions to the current implementation to improve performance for 1000+ validators
```suggestion
* introduce SIMD instructions to the current implementation to improve performance for 1000+ validators
```

2023-07-21 11:11 UTC, ordian commented on applications/reed-solomon-perf.md
> +3. add SMID to the current implementation
```suggestion
3. add SIMD to the current implementation
```

2023-07-21 11:11 UTC, ordian commented on applications/reed-solomon-perf.md
> +| 1. | SMID perf | Implement SMID |
```suggestion
| 1. | SIMD perf | Implement SIMD |
```

2023-07-21 11:14 UTC, ordian commented
Also relevant: https://github.com/paritytech/polkadot/issues/7505

2023-07-21 11:23 UTC, burdges commented
> Also relevant: https://github.com/paritytech/polkadot/issues/7505

This is internal to how polkadot uses the chunks.  I don't care who does this work of course.  And the migration is a simply an if check to start the shuffling at some fixed block height, plus something to deprecate hosts who won't have this check.  I'll send some emails about my generalized Feistel algorithm question for that.

2023-07-21 11:25 UTC, ordian commented
I meant making the encoding systematic, which is currently not on the https://github.com/paritytech/reed-solomon-novelpoly/ level IIUC. @drahnr please correct me if I'm wrong

2023-07-21 11:28 UTC, burdges commented
I'd thought it was systematic from the beginning, but if not then yeah reevaluate that choice.

2023-07-21 14:40 UTC, drahnr commented
> Hey Bernhard :)
> 
> When exploring SIMD, would be great to do runtime feature detection, like in [dalek-cryptography/curve25519-dalek#523](https://github.com/dalek-cryptography/curve25519-dalek/pull/523)

Will do!

2023-07-21 14:40 UTC, drahnr commented
> I'd thought it was systematic from the beginning, but if not then yeah we should recall why we made that choice, but that'd be larger than this proposal.

From the paper, it should be, I didn't verify the impl yet

2023-07-24 12:03 UTC, Noc2 requested changes
Thanks for the application. I'm generally happy to go ahead with it. Just a few quick comments: 
- Feel free to remove the template text that isn't bold from the application, like "We expect the teams to already have a solid idea about your project's expected final state. Therefore, we ask the teams to submit (where relevant)". This makes it hard to read.
- Could you add the programming language to the deliverables? 
- Also feel free to add 

> When exploring SIMD, would be great to do runtime feature detection, like in https://github.com/dalek-cryptography/curve25519-dalek/pull/523

2023-07-24 13:17 UTC, ordian approved these changes

2023-07-24 14:00 UTC, Noc2 approved these changes
Thanks for the update. I'm happy to go ahead with it.

2023-07-24 22:05 UTC, xlc approved these changes

2023-07-25 02:03 UTC, merged

2023-07-25 07:27 UTC, riusricardo commented
@drahnr Thanks for the application. After merging, I realized that there's a discrepancy. Could you please clarify the difference in the total amount and the amounts per milestone? The sum doesn't add up.

2023-07-25 08:29 UTC, drahnr commented
See PR #3 which addresses the inconsistencies

2023-08-07 06:13 UTC, drahnr commented
> > Hey Bernhard :)
> > When exploring SIMD, would be great to do runtime feature detection, like in [dalek-cryptography/curve25519-dalek#523](https://github.com/dalek-cryptography/curve25519-dalek/pull/523)
> 
> Will do, given it doesn't explode time wise

After a first time assessment, it will not be part of the milestone 1 implementation.

2024-02-20 11:04 UTC, drahnr commented
A bit of brief update, I am currently pending some clarification on the gao mateer paper by the authors. Otherwise it's well on track to delivery, albeit a bit behind schedule for a bag of personal reasons (good ones only!).

2024-02-20 13:33 UTC, ordian commented
jFYI: https://github.com/paritytech/reed-solomon-novelpoly/issues/40, SIMD impl has a 10x speedup over non-SIMD (also in the original C++ leopard lib), so it's worth looking into more closely.

2024-02-21 10:08 UTC, drahnr commented
> jFYI: [paritytech/reed-solomon-novelpoly#40](https://github.com/paritytech/reed-solomon-novelpoly/issues/40), SIMD impl has a 10x speedup over non-SIMD (also in the original C++ leopard lib), so it's worth looking into more closely.

Jeff already mentioned it. I'd see that as part of #10 , going to make it explicit there, I don't have capacity to take on unpaid additional work beyond what I do already as open source work unfortunately and part 1 is already closed.

2024-04-23 08:48 UTC, drahnr commented
So turns out I underestimated the time required for it. It's still going to be a bit before there are results. Just to be clear, further proposals will come in at a more realistic rate taking into account the uncertainty bits more.